### ISSUE TITLE
Ticket 1 - Installing Vitest

### ISSUE THREAD

**Issue by IOLV** [SchoolOfCode/bc17-w6-d1-workshop-unit-testing-jka-tech-titans#1]
```[tasklist]
### Tasks
- [x] Clone the repository to your machine
- [x] Change directory (cd) into 'proof-of-concepts' folder
- [x] Install 'Vitest' as a dev depency using 'npm install -d vitest'
```
