### ISSUE TITLE
Ticket 2 - Writing a basic test skeleton

### ISSUE THREAD

**Issue by IOLV** [SchoolOfCode/bc17-w6-d1-workshop-unit-testing-jka-tech-titans#2]
```[tasklist]
### Tasks
- [x] Within the proof-of-concept project, create a file called bare-bones.test.js
- [x] Inside the bare-bones.test.js file, import test from vitest
- [x] Call test to define a new test named "bare bones test should pass" that doesn't do anything yet.
```
